name: Docker image

on:
  push:
    branches:
    - main
    paths:
    - 'Dockerfile.rootfs'
    - 'Dockerfile.builder'

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm64]
    permissions:
      contents: read
      packages: write
    if: github.repository == 'ganyao114/winemu-builder'
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      with:
        image: tonistiigi/binfmt:latest
        platforms: arm64
    - name: Build
      run: |
        docker build --platform ${{ matrix.platform }} --tag ganyao114/winemu-rootfs:latest --file Dockerfile.rootfs .
        docker tag ganyao114/winemu-rootfs:latest ghcr.io/ganyao114/winemu-rootfs:latest
        docker build --platform ${{ matrix.platform }} --tag ganyao114/winemu-builder:latest --file Dockerfile.builder .
        docker tag ganyao114/winemu-builder:latest ghcr.io/ganyao114/winemu-builder:latest
        sudo docker create --name temp_container ganyao114/winemu-rootfs
        docker export temp_container > imagefs.tar
    - name: Upload rootfs
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: imagefs.tar
        # A file, directory or wildcard pattern that describes what to upload
        path: imagefs.tar
    - name: Login to GHCR
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.repository == 'ganyao114/winemu-builder'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.repository == 'ganyao114/winemu-builder'
      run: |
        # ghcr.io seem to be unstable sometimes. It may suddenly drop connection
        # during docker push when some layers are already uploaded. The workaround
        # is to retry again 1 or 2 more times.
        for registry in "ghcr.io/"; do
          for image in winemu-builder; do
            for t in 1 2 3; do
              if docker push "${registry}ganyao114/${image}:latest"; then
                break
              else
                if [ "$t" = "3" ]; then
                  echo "Giving up after 3 attempts"
                  exit 1
                fi
                sleep 20
              fi
            done
          done
        done
